version: '3'

services:
  db:
    image: registry.gitlab.com/zisoft/image/awareness/db-3-package
    environment:
      - MYSQL_USER=zisoft
      - MYSQL_DATABASE=zisoft
      - MYSQL_PASSWORD=Password1
      - MYSQL_ROOT_PASSWORD=Password1
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: registry.gitlab.com/zisoft/image/awareness/web-3-package
  ui:
    image: registry.gitlab.com/zisoft/image/awareness/ui-3-package
  worker:
    image: registry.gitlab.com/zisoft/image/awareness/worker-3-package
  meta:
    image: registry.gitlab.com/zisoft/image/awareness/meta-3-package
    environment:
      - MB_DB_FILE=/tmp/metabase.db
  proxy:
    image: registry.gitlab.com/zisoft/image/awareness/proxy-3-package
    ports:
      - "80:80"
      - "443:443"
  cron:
    image: registry.gitlab.com/zisoft/image/awareness/cron-3-package
    
volumes:
    db_data:
