apiVersion: v1
kind: Service
metadata:
  name: zisoft-db
  labels:
    app: zisoft
spec:
  ports:
    - port: 3306
  selector:
    app: zisoft
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: zisoft
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zisoft-db
  labels:
    app: zisoft
    tier: mysql
spec:
  selector:
    matchLabels:
      app: zisoft
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zisoft
        tier: mysql
    spec:
      containers:
      - image: registry.gitlab.com/omarabdalhamid/awareness_swarm/db:20_11_2019
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
